[env:lilygo-t-display-s3]
platform = espressif32@6.5.0
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps =
  moononournation/GFX Library for Arduino@1.4.9
  bitbank2/JPEGDEC@1.8.4
  bblanchon/ArduinoJson@6.21.6
board_build.embed_files =
  data/deepseek.jpg
  data/deepseek-offline.jpg
  data/gpt.jpg
  data/claude.jpg
  data/gemini.jpg
  data/x509_crt_bundle.bin
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
